# Generated by Django 6.0.5 on 2026-06-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to; null for superusers/admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('inspector', 'Inspector'), ('reviewer', 'Reviewer')], default='inspector', help_text='User role defining access permissions and capabilities', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Specific site/location where user operates; optional if user covers multiple sites', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organizations.site'),
        ),
    ]
