# Generated by Django 6.0.5 on 2026-06-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that works with this supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization'),
        ),
    ]
